language: go

services:
  - docker

go:
  - 1.13.x

jobs:
  include:
    - stage: test
      install:
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.24.0
      script:
        - ./scripts/test.sh
        - ./bin/golangci-lint run --timeout 5m --exclude "\.pb.*\.go" --exclude "_strings\.go" --exclude "_test\.go" --exclude "not checked.+Close" ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: push
      install: skip
      script:
        - ./scripts/build.sh
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - ./scripts/push.sh

stages:
  - name: test
  - name: push
    if: branch = master and not type = pull_request
